version: "3"
services:
  spark:
    image: jupyter/sparkmagic-livy
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark
    ports:
      - "8998:8998"
  jupyter:
    image: jupyter/sparkmagic
    #image: darkice01/sparkmagic-minimal
    #image: darkice01/sparkmagic-scipy
    #image: darkice01/sparkmagic-r
    #image: darkice01/sparkmagic-tensorflow
    #image: darkice01/sparkmagic-datascience
    #image: darkice01/sparkmagic-pyspark
    #image: darkice01/sparkmagic-all
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      #dockerfile: Dockerfile.jupyter-minimal
      #dockerfile: Dockerfile.jupyter-scipy
      #dockerfile: Dockerfile.jupyter-r
      #dockerfile: Dockerfile.jupyter-tensorflow
      #dockerfile: Dockerfile.jupyter-datascience
      #dockerfile: Dockerfile.jupyter-pyspark
      #dockerfile: Dockerfile.jupyter-all
      args:
        dev_mode: "false"
    links:
      - spark
    ports:
      - "8888:8888"
