version: "3"
services:
  spark:
    image: jmeidam/jupyter-sparkmagic-livy
    hostname: spark
    ports:
      - "8998:8998"
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "true"
    links:
      - spark
    ports:
      - "8888:8888"
